apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-service
  labels:
    app: fact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fact-service
  template:
    metadata:
      labels:
        app: fact-service
    spec:
      containers:
      - name: fact-service
        image: terranblake/fact-service
        command: ["npm", "start"]
        env:
          - name: MONGODB
            value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/fundamentals?replicaSet=rs0
          - name: REDIS
            value: redis