apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: nginx
    targetPort: 5000
  selector:
    app: metadata-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  labels:
    app: metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
      - name: metadata-service
        image: terranblake/metadata-service
        command: ["python", "./src/server.py"]
        env:
          - name: PORT
            value: "5000"